branches:
  except:
  - /.*(.tmp)$/

language: rust
matrix:
  include:
    # This version is tested to avoid unintentional bumping of the minimum supported Rust version
    - rust: 1.30.0
      env:
        - LABEL="msrv"
      script:
        - cargo test
    - rust: stable
      env:
        - LABEL="no-std"
      script:
        - rustup target add thumbv6m-none-eabi
        - cargo build --features example_generated --target thumbv6m-none-eabi
    - rust: nightly
      env:
        - LABEL="compiletest"
      script:
        - cargo test
        - cargo test -p test_suite
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
  allow_failures:
    - rust: nightly

sudo: false
script:
  - cargo test --all

notifications:
  email:
    on_success: never
