[package]

name = "bitflags"
version = "0.3.2"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/bitflags"
homepage = "https://github.com/rust-lang/bitflags"
documentation = "http://doc.rust-lang.org/bitflags"
description = """
A macro to generate structures which behave like bitflags.
"""
