[package]

name = "bitflags"
version = "0.8.0" # also update number in readme for breaking changes
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
keywords = ["bit", "bitmask", "bitflags"]
readme = "README.md"
repository = "https://github.com/rust-lang/bitflags"
homepage = "https://github.com/rust-lang/bitflags"
documentation = "https://doc.rust-lang.org/bitflags"
description = """
A macro to generate structures which behave like bitflags.
"""

[features]
unstable_testing = []
